import type { Annotation } from '@/components/editor/ImageAnnotationEditor';
import { buildClickHighlight } from '@/lib/annotations';
import { hasDecorativeActionGlyph, stripDecorativeActionGlyphs } from '@/lib/action-copy';

export type AutoAnnotationStep = {
  number: number;
  actionTitle: string;
  pageUrl?: string | null;
  annotations?: Annotation[];
  click_x?: number | null;
  click_y?: number | null;
  element_rect?: { x: number; y: number; width: number; height: number } | null;
  type_text?: string | null;
  targetContext?: { accessibleName?: string | null } | null;
};

function usesTextOnlyAnnotation(step: AutoAnnotationStep): boolean {
  const capturedLabel = step.targetContext?.accessibleName || step.actionTitle;
  return hasDecorativeActionGlyph(capturedLabel)
    || hasDecorativeActionGlyph(step.actionTitle);
}

function textOnlyAnnotations(annotations: Annotation[]): Annotation[] {
  return annotations
    .filter(annotation => annotation.type === 'text')
    .map(annotation => ({
      ...annotation,
      text: stripDecorativeActionGlyphs(annotation.text),
    }));
}

export function buildAutoAnnotation(step: AutoAnnotationStep): Annotation[] {
  const useTextOnlyAnnotation = usesTextOnlyAnnotation(step);
  const rawLabel = step.actionTitle
    ? stripDecorativeActionGlyphs(step.actionTitle).replace(/^입력,?\s*/i, '').trim()
    : '';
  const label = normalizeAutoAnnotationLabel(rawLabel, step.pageUrl);
  const r = step.element_rect;
  let rect: { x: number; y: number; width: number; height: number };

  if (r && r.width > 0 && r.height > 0) {
    rect = r;
  } else if (step.click_x != null && step.click_y != null && step.click_x > 0 && step.click_x < 100 && step.click_y > 0 && step.click_y < 100) {
    const cx = step.click_x / 100;
    const cy = step.click_y / 100;
    const x = Math.max(0, cx - 0.05);
    const y = Math.max(0, cy - 0.02);
    rect = { x, y, width: Math.min(0.10, 1 - x), height: Math.min(0.04, 1 - y) };
  } else {
    return [];
  }

  const annotations = buildClickHighlight({
    elementRect: rect,
    stepNumber: step.number,
    label,
    clickX: step.click_x != null ? step.click_x / 100 : null,
    clickY: step.click_y != null ? step.click_y / 100 : null,
    actionType: step.type_text ? 'type' : null,
  });
  return useTextOnlyAnnotation
    ? textOnlyAnnotations(annotations)
    : annotations;
}

export function displayAutoAnnotationsFor(step: AutoAnnotationStep): Annotation[] {
  if (usesTextOnlyAnnotation(step) && isAutoGeneratedAnnotationSet(step)) {
    const textOnly = textOnlyAnnotations(step.annotations ?? []);
    if (textOnly.length > 0) return textOnly;
  }
  const shouldRefresh = isAutoGeneratedAnnotationSet(step)
    && (isOversizedRect(step.element_rect) || isClickOutsideRect(step))
    && step.click_x != null
    && step.click_y != null
    && step.click_x > 0
    && step.click_x < 100
    && step.click_y > 0
    && step.click_y < 100;
  if (shouldRefresh) {
    const annotations = buildAutoAnnotation(step);
    if (annotations.length > 0) return annotations;
  }
  return step.annotations ?? [];
}

function normalizeAutoAnnotationLabel(label: string, pageUrl?: string | null): string {
  const text = label.trim();
  if (/^(search|검색)(\s*(클릭|확인|선택|입력|이동))?$/i.test(text)) return '검색창 선택';
  if (pageUrl && /checkout|payment|pay|order|orders|주문|결제/i.test(pageUrl) && /장바구니\s*담기|add\s*to\s*cart/i.test(text)) {
    return '주문 정보 확인';
  }
  if (!text || text.length > 18 || /^(button|link|menu|click|icon|image|svg|div|span)\s*(클릭|확인|선택|입력|이동)?$/i.test(text)) {
    return '대상 확인';
  }
  return text;
}

function isOversizedRect(rect?: AutoAnnotationStep['element_rect']): boolean {
  if (!rect) return false;
  return rect.width > 0.34 || rect.height > 0.16 || rect.width * rect.height > 0.055;
}

function isClickOutsideRect(step: AutoAnnotationStep): boolean {
  const rect = step.element_rect;
  if (!rect || step.click_x == null || step.click_y == null) return false;
  if (step.click_x <= 0 || step.click_x >= 100 || step.click_y <= 0 || step.click_y >= 100) return false;
  const x = step.click_x / 100;
  const y = step.click_y / 100;
  const tolerance = 0.025;
  return x < rect.x - tolerance
    || x > rect.x + rect.width + tolerance
    || y < rect.y - tolerance
    || y > rect.y + rect.height + tolerance;
}

function isAutoGeneratedAnnotationSet(step: AutoAnnotationStep): boolean {
  const annotations = step.annotations ?? [];
  if (annotations.length === 0) return false;
  const prefix = `guidde-${step.number}-`;
  return annotations.some(a => typeof a.id === 'string' && a.id.startsWith(prefix))
    && annotations.every(a => typeof a.id === 'string' && a.id.startsWith(prefix));
}
